# inspired from https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/.travis.yml

language: php

cache:
  directories:
    - $HOME/.composer/cache/files

branches:
  only:
    - master

matrix:
  include:
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.2
    - php: 7.3
    - php: 7.4
  allow_failures:
    # @TODO remove when atoum will support php7.4
    - php: 7.4

before_install:
  - phpenv config-rm xdebug.ini || true

install:
  - composer update $COMPOSER_FLAGS --prefer-dist -n
  - if [ "$COMPOSER_PREFER" = "lowest" ]; then composer update --prefer-lowest -n; fi;

script:
  - make ci
