language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_script:
  - phpenv config-rm xdebug.ini

branches:
  only:
    - master

install:
  - composer install -n --dev

script:
  - bin/coke
  - bin/atoum
