services:
    m6web.data_collector.guzzlehttp:
        class: M6Web\Bundle\GuzzleHttpBundle\DataCollector\GuzzleHttpDataCollector
        tags:
            - { name: data_collector, template: '@M6WebGuzzleHttp/Collector/guzzlehttp.html.twig', id: 'guzzlehttp' }
            - { name: kernel.event_listener, event: m6web.guzzlehttp, method: onGuzzleHttpCommand }
